Repository brain-tec/training, pull requests merged in 2019-03, with the labels that each got.

#22 Full Technical Training (after Raul Rev. 1)
  openacademy/__init__.py
  openacademy/__manifest__.py
  openacademy/data/schedulers.xml
  openacademy/demo/demo_data.xml
  openacademy/i18n/es.po
  openacademy/models/__init__.py
  openacademy/models/course.py
  openacademy/models/partner.py
  openacademy/models/session.py
  openacademy/reports/session_reports.xml
  openacademy/scripts/session_users_json.py
  openacademy/scripts/session_users_xml.py
  openacademy/security/ir.model.access.csv
  openacademy/security/security.xml
  openacademy/tests/__init__.py
  openacademy/tests/test_my_test.py
  openacademy/views/course_views.xml
  openacademy/views/menu.xml
  openacademy/views/partner_views.xml
  openacademy/views/session_views.xml
  openacademy/wizard/__init__.py
  openacademy/wizard/wizard.py
  openacademy/wizard/wizard_view.xml
Labels: 11.0.orja1

#17 11.0.frna1
  openacademy/__init__.py
  openacademy/__manifest__.py
  openacademy/data/to_done_cronjob.xml
  openacademy/demo/courses_demo_data.xml
  openacademy/demo/sessions_demo_data.xml
  openacademy/i18n/es.po
  openacademy/models/__init__.py
  openacademy/models/course.py
  openacademy/models/partner_inheritance.py
  openacademy/models/session.py
  openacademy/reports/session_reports.xml
  openacademy/security/ir.model.access.csv
  openacademy/security/security.xml
  openacademy/tests/__init__.py
  openacademy/tests/test_exercise.py
  openacademy/views/course_views.xml
  openacademy/views/courses_menu.xml
  openacademy/views/demo_data.xml
  openacademy/views/partner_menu.xml
  openacademy/views/partner_views.xml
  openacademy/views/session_views.xml
  openacademy/views/sessions_menu.xml
  openacademy/views/wizard_view.xml
  openacademy/wizard/__init__.py
  openacademy/wizard/add_sessions_wizard.py
  rpc/json_rpc.py
  rpc/xml_rpc.py
Labels: 11.0.frna1

#14 11.0.dherreros
  openacademy/__init__.py
  openacademy/__manifest__.py
  openacademy/data/cron_donedate.xml
  openacademy/demo/mydemodata.xml
  openacademy/demo/session_demo_data.xml
  openacademy/demo/teachers.xml
  openacademy/i18n/es.po
  openacademy/models/__init__.py
  openacademy/models/curso.py
  openacademy/models/partner_EXT.py
  openacademy/models/session.py
  openacademy/report/report_view.xml
  openacademy/report/session.xml
  openacademy/scripts/json-rpc_session_scripts.py
  openacademy/scripts/xml-rpc_session_scripts.py
  openacademy/security/ir.model.access.csv
  openacademy/security/security.xml
  openacademy/tests/__init__.py
  openacademy/tests/test_session.py
  openacademy/tests/test_wizard.py
  openacademy/views/menu.xml
  openacademy/views/partner_ext.xml
  openacademy/views/session_views.xml
  openacademy/views/vistas.xml
  openacademy/wizard/__init__.py
  openacademy/wizard/wizard.py
  openacademy/wizard/wizard_view.xml
Labels: 11.0.dherreros

#25 11.0.panken1
  openacademy/__init__.py
  openacademy/__manifest__.py
  openacademy/data/base_data.xml
  openacademy/data/cron.xml
  openacademy/demo/course_demo.xml
  openacademy/i18n/fr_CH.po
  openacademy/models/__init__.py
  openacademy/models/course.py
  openacademy/models/partner.py
  openacademy/models/session.py
  openacademy/reports/report_session.xml
  openacademy/scripts/XML_RPC.py
  openacademy/security/ir.model.access.csv
  openacademy/security/security.xml
  openacademy/tests/__init__.py
  openacademy/tests/test_session.py
  openacademy/views/course_ext_view.xml
  openacademy/views/course_view.xml
  openacademy/views/session_view.xml
  openacademy/wizard/__init__.py
  openacademy/wizard/wizard.py
  openacademy/wizard/wizard_view.xml
Labels: 11.0.panken
